pnpm:
  overrides:
    typescript: "^5.4.0"
    react: "^19.0.0"
    react-dom: "^19.0.0"
    next: "^15.0.0"

node-linker: hoisted

shamefully-hoist: true

packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"
